//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCComm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Alarms : global::System.Configuration.ApplicationSettingsBase {
        
        private static Alarms defaultInstance = ((Alarms)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Alarms())));
        
        public static Alarms Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Online")]
        public string Online_Text {
            get {
                return ((string)(this["Online_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color Online_Color {
            get {
                return ((global::System.Drawing.Color)(this["Online_Color"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System OK")]
        public string OK_Text {
            get {
                return ((string)(this["OK_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color OK_Color {
            get {
                return ((global::System.Drawing.Color)(this["OK_Color"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Voltage: Low")]
        public string SysVoltLo_Text {
            get {
                return ((string)(this["SysVoltLo_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color SysVoltLo_Color {
            get {
                return ((global::System.Drawing.Color)(this["SysVoltLo_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double SysVoltLo_Limit {
            get {
                return ((double)(this["SysVoltLo_Limit"]));
            }
            set {
                this["SysVoltLo_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SysVoltLo_Value {
            get {
                return ((int)(this["SysVoltLo_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" V")]
        public string SysVoltLo_Denom {
            get {
                return ((string)(this["SysVoltLo_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Voltage: Very Low")]
        public string SysVoltVeryLo_Text {
            get {
                return ((string)(this["SysVoltVeryLo_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SysVoltVeryLo_Color {
            get {
                return ((global::System.Drawing.Color)(this["SysVoltVeryLo_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.5")]
        public double SysVoltVeryLo_Limit {
            get {
                return ((double)(this["SysVoltVeryLo_Limit"]));
            }
            set {
                this["SysVoltVeryLo_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SysVoltVeryLo_Value {
            get {
                return ((int)(this["SysVoltVeryLo_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" V")]
        public string SysVoltVeryLo_Denom {
            get {
                return ((string)(this["SysVoltVeryLo_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Int. Temperature: High")]
        public string SysIntTempHi_Text {
            get {
                return ((string)(this["SysIntTempHi_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color SysIntTempHi_Color {
            get {
                return ((global::System.Drawing.Color)(this["SysIntTempHi_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double SysIntTempHi_Limit {
            get {
                return ((double)(this["SysIntTempHi_Limit"]));
            }
            set {
                this["SysIntTempHi_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SysIntTempHi_Value {
            get {
                return ((int)(this["SysIntTempHi_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("° C")]
        public string SysIntTempHi_Denom {
            get {
                return ((string)(this["SysIntTempHi_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Int. Temperature: Very High")]
        public string SysIntTempVeryHi_Text {
            get {
                return ((string)(this["SysIntTempVeryHi_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SysIntTempVeryHi_Color {
            get {
                return ((global::System.Drawing.Color)(this["SysIntTempVeryHi_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double SysIntTempVeryHi_Limit {
            get {
                return ((double)(this["SysIntTempVeryHi_Limit"]));
            }
            set {
                this["SysIntTempVeryHi_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SysIntTempVeryHi_Value {
            get {
                return ((int)(this["SysIntTempVeryHi_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("° C")]
        public string SysIntTempVeryHi_Denom {
            get {
                return ((string)(this["SysIntTempVeryHi_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tamper: Loop Open!")]
        public string Tamper_Text {
            get {
                return ((string)(this["Tamper_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Tamper_Color {
            get {
                return ((global::System.Drawing.Color)(this["Tamper_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double Tamper_Limit {
            get {
                return ((double)(this["Tamper_Limit"]));
            }
            set {
                this["Tamper_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Tamper_Value {
            get {
                return ((int)(this["Tamper_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" V")]
        public string Tamper_Denom {
            get {
                return ((string)(this["Tamper_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Module: Unit Timeout!")]
        public string Timeout_Text {
            get {
                return ((string)(this["Timeout_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Timeout_Color {
            get {
                return ((global::System.Drawing.Color)(this["Timeout_Color"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fire: Smoke Detected!")]
        public string Fire_Text {
            get {
                return ((string)(this["Fire_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Fire_Color {
            get {
                return ((global::System.Drawing.Color)(this["Fire_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double Fire_Limit {
            get {
                return ((double)(this["Fire_Limit"]));
            }
            set {
                this["Fire_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Fire_Value {
            get {
                return ((int)(this["Fire_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" V")]
        public string Fire_Denom {
            get {
                return ((string)(this["Fire_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alarm System: Triggered!")]
        public string Alarm_Text {
            get {
                return ((string)(this["Alarm_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Alarm_Color {
            get {
                return ((global::System.Drawing.Color)(this["Alarm_Color"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Ext. Temperature: High")]
        public string SysExtTempHi_Text {
            get {
                return ((string)(this["SysExtTempHi_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color SysExtTempHi_Color {
            get {
                return ((global::System.Drawing.Color)(this["SysExtTempHi_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double SysExtTempHi_Limit {
            get {
                return ((double)(this["SysExtTempHi_Limit"]));
            }
            set {
                this["SysExtTempHi_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SysExtTempHi_Value {
            get {
                return ((int)(this["SysExtTempHi_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("° C")]
        public string SysExtTempHi_Denom {
            get {
                return ((string)(this["SysExtTempHi_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ext. Temperature Low")]
        public string ExtTempLo_Text {
            get {
                return ((string)(this["ExtTempLo_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color ExtTempLo_Color {
            get {
                return ((global::System.Drawing.Color)(this["ExtTempLo_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double ExtTempLo_Limit {
            get {
                return ((double)(this["ExtTempLo_Limit"]));
            }
            set {
                this["ExtTempLo_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ExtTempLo_Value {
            get {
                return ((int)(this["ExtTempLo_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("° C")]
        public string ExtTempLo_Denom {
            get {
                return ((string)(this["ExtTempLo_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC Battery: Low")]
        public string BatteryLo_Text {
            get {
                return ((string)(this["BatteryLo_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color BatteryLo_Color {
            get {
                return ((global::System.Drawing.Color)(this["BatteryLo_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double BatteryLo_Limit {
            get {
                return ((double)(this["BatteryLo_Limit"]));
            }
            set {
                this["BatteryLo_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int BatteryLo_Value {
            get {
                return ((int)(this["BatteryLo_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" %")]
        public string BatteryLo_Denom {
            get {
                return ((string)(this["BatteryLo_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC Battery: Very Low")]
        public string BatteryVeryLo_Text {
            get {
                return ((string)(this["BatteryVeryLo_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BatteryVeryLo_Color {
            get {
                return ((global::System.Drawing.Color)(this["BatteryVeryLo_Color"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double BatteryVeryLo_Limit {
            get {
                return ((double)(this["BatteryVeryLo_Limit"]));
            }
            set {
                this["BatteryVeryLo_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int BatteryVeryLo_Value {
            get {
                return ((int)(this["BatteryVeryLo_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" %")]
        public string BatteryVeryLo_Denom {
            get {
                return ((string)(this["BatteryVeryLo_Denom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC Power: Offline")]
        public string PowerOffline_Text {
            get {
                return ((string)(this["PowerOffline_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color PowerOffline_Color {
            get {
                return ((global::System.Drawing.Color)(this["PowerOffline_Color"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Online_Image {
            get {
                return ((bool)(this["Online_Image"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OK_Image {
            get {
                return ((bool)(this["OK_Image"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysVoltLo_Image {
            get {
                return ((bool)(this["SysVoltLo_Image"]));
            }
            set {
                this["SysVoltLo_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysVoltVeryLo_Image {
            get {
                return ((bool)(this["SysVoltVeryLo_Image"]));
            }
            set {
                this["SysVoltVeryLo_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysTempHi_Image {
            get {
                return ((bool)(this["SysTempHi_Image"]));
            }
            set {
                this["SysTempHi_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysTempVeryHi_Image {
            get {
                return ((bool)(this["SysTempVeryHi_Image"]));
            }
            set {
                this["SysTempVeryHi_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tamper_Image {
            get {
                return ((bool)(this["Tamper_Image"]));
            }
            set {
                this["Tamper_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timeout_Image {
            get {
                return ((bool)(this["Timeout_Image"]));
            }
            set {
                this["Timeout_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Fire_Image {
            get {
                return ((bool)(this["Fire_Image"]));
            }
            set {
                this["Fire_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Alarm_Image {
            get {
                return ((bool)(this["Alarm_Image"]));
            }
            set {
                this["Alarm_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysExtTempHi_Image {
            get {
                return ((bool)(this["SysExtTempHi_Image"]));
            }
            set {
                this["SysExtTempHi_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtTempLo_Image {
            get {
                return ((bool)(this["ExtTempLo_Image"]));
            }
            set {
                this["ExtTempLo_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BatteryLo_Image {
            get {
                return ((bool)(this["BatteryLo_Image"]));
            }
            set {
                this["BatteryLo_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BatteryVeryLo_Image {
            get {
                return ((bool)(this["BatteryVeryLo_Image"]));
            }
            set {
                this["BatteryVeryLo_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PowerOffline_Image {
            get {
                return ((bool)(this["PowerOffline_Image"]));
            }
            set {
                this["PowerOffline_Image"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Alarm_Value {
            get {
                return ((int)(this["Alarm_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PowerOffline_Value {
            get {
                return ((int)(this["PowerOffline_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Timeout_Value {
            get {
                return ((int)(this["Timeout_Value"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SysExtTempVeryHi_Color {
            get {
                return ((global::System.Drawing.Color)(this["SysExtTempVeryHi_Color"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("° C")]
        public string SysExtTempVeryHi_Denom {
            get {
                return ((string)(this["SysExtTempVeryHi_Denom"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double SysExtTempVeryHi_Limit {
            get {
                return ((double)(this["SysExtTempVeryHi_Limit"]));
            }
            set {
                this["SysExtTempVeryHi_Limit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Ext. Temperature: Very High")]
        public string SysExtTempVeryHi_Text {
            get {
                return ((string)(this["SysExtTempVeryHi_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SysExtTempVeryHi_Value {
            get {
                return ((int)(this["SysExtTempVeryHi_Value"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysExtTempVeryHi_Image {
            get {
                return ((bool)(this["SysExtTempVeryHi_Image"]));
            }
            set {
                this["SysExtTempVeryHi_Image"] = value;
            }
        }
    }
}
